Build Evergreen 4.0 x86_64 only
This addresses the Source Compatibility Suite failure

```
error: The linked and embedded framework 'Sparkle.framework' is missing
one or more architectures required by this target: arm64. (in target
'Evergreen' from project 'Evergreen')
```

Addresses rdar://70533579